### ISSUE TITLE
How to set the options of default grpc server?

### ISSUE THREAD

**Issue by skight-shen** [fengsp/django-grpc-framework#36]
It  seems there is no api to set the options of grpc server. The options can be set only when initialize the grpc server.

I encountered an issue says "Received message larger than max (4750306 vs. 4194304)". I know how to solve it by setting the options of customized grpc server. 

But I'd like to change the options of the default grpc server and i didn't found the entry of the default server. Does anyone can help or any suggestions?

**Comment by mlazowik** [comment]
Options would have to be passed here: https://github.com/fengsp/django-grpc-framework/blob/master/django_grpc_framework/management/commands/grpcrunserver.py#L61, so changes to this lib are needed to support passing options.

**Comment by mlazowik** [comment]
Made a patch for this in a fork: https://github.com/qedsoftware/django-grpc-framework/commit/5a498e47aa763a67163c42405936978b7f851902

**Comment by skight-shen** [comment]
> 

@mlazowik Thank you very much. It works!
